name: CI/CD Django with Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Run Docker container with volume mount for SQLite
      run: |
        docker stop myapp-container || true
        docker rm myapp-container || true
        docker run -d -p 8008:8008 \
          -v ${{ github.workspace }}/db.sqlite3:/app/db.sqlite3 \
          --name myapp-container myapp:latest

    - name: Run migrations
      run: docker exec myapp-container python manage.py migrate
